# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
use_frameworks!
target 'TVOnline' do
pod 'Masonry'
pod 'AFNetworking'
pod 'YYKit'
pod 'MJRefresh'

pod 'MBProgressHUD'

end
